### ISSUE TITLE
Baseline MAINTAINERS, CODEOWNERS, and external collaborator permissions

### ISSUE THREAD

**Issue by dblock** [opensearch-project/sql-cli#10]
Follow https://github.com/opensearch-project/.github/issues/125 to baseline MAINTAINERS, CODEOWNERS, and external collaborator permissions.

Close this issue when:

1. [MAINTAINERS.md](MAINTAINERS.md) has the correct list of project maintainers.
2. [CODEOWNERS](CODEOWNERS) exists and has the correct list of aliases.
3. Repo permissions only contain individual aliases as collaborators with maintain rights, admin, and triage teams. 
4. All other teams are removed from repo permissions.

If this repo's permissions was already baselined, please confirm the above when closing this issue.

**Comment by dblock** [comment]
Permissions are incorrect. 19 people have maintain rights to this repo.


Please work with a
![Screenshot 2023-03-23 at 10 50 27 AM](https://user-images.githubusercontent.com/542335/227241739-4323b91c-5e80-4813-ba53-b08ed40378a4.png)
dmin to adjust.

**Comment by bbarani** [comment]
Added the users listed in MAINTAINERS.md file as maintainers of this repo. @anirudha  Please add CODEOWNERS file under .github directory with the maintainers list. CC: @dblock @CEHENKLE 

I am not able to add [MaxKsyunz](https://github.com/MaxKsyunz) and [Yury-Fridlyand](https://github.com/Yury-Fridlyand) as they are not part of the organization yet.

**Comment by derek-ho** [comment]
This is done pending adding max and yury to github, which I have opened a ticket for

**Comment by dblock** [comment]
Verified, thx.
