### ISSUE TITLE
[BUG] Bump Requests version > 2.31.0

### ISSUE THREAD

**Issue by penghuo** [opensearch-project/sql-cli#20]
**What is the bug?**
https://github.com/advisories/GHSA-j8r2-6x86-q33q

**Do you have any screenshots?**

**Do you have any additional context?**
Add any other context about the problem.

**Comment by Yury-Fridlyand** [comment]
`requests` is a dependency of `requests-aws4auth==0.9`. `requests-aws4auth==0.9` does not require specific version of `requests`, so `pip` will install latest on clean install or update.
`requests-aws4auth@0.9` requirements: https://github.com/tedder/requests-aws4auth/blob/9177c77fff5cdef0605343d4ac87cb61f681e10b/setup.py#L47
No-op from our side I suppose.
